# Generated by Django 2.2.13 on 2020-06-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='distance_run',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
