# Generated by Django 2.2.13 on 2020-07-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200616_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='kategorie',
            field=models.CharField(choices=[('-', '-'), ('ATT', 'Allgemeine Tipps und Tricks'), ('EB', 'Ernährungsbericht'), ('AB', 'Ausrüstungsbericht'), ('TF', 'Trainingsfortschritt'), ('MT', 'Motivationstipps'), ('LGT', 'Laufgruppentrainingseinheit')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='distance_run',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
